### ISSUE TITLE
Use basedir command line flag when data-commons flag is also set

### ISSUE THREAD

**Issue by theferrit32** [stevencox/cwltool#2]
Allow the easy use of job files with local relative paths by prepending an absolute path to them when data-commons is used. 

Like --basedir=/renci/irods

**Comment by theferrit32** [comment]
basedir flag is not handled or documented in upstream cwltool, so I went with a different approach. 

cwltool will treat all relative paths in the job file as being relative to the location of the job file.  If referencing files in iRODS this means that the job file must also be in iRODS, and the iRODS mountpoint must be the same as the mesos worker nodes (currently /renci/irods).  

Output file locations will also be set to be relative to this location, and the --outdir command line flag is currently ignored, though the goal is to have an implementation of it later.

In order to set this up consistently in an easy way, it is recommended to just build and use the docker workspace set up for this: https://github.com/theferrit32/data-commons-workspace

**Comment by stevencox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a "datacommons" flag to control execution of modified features.](https://trello.com/c/RYYcJ7Ha/3-add-a-datacommons-flag-to-control-execution-of-modified-features)
