### ISSUE TITLE
WebDAV

### ISSUE THREAD

**Issue by stevencox** [stevencox/cwltool#4]
Determine if iRODS iCAT in a Docker container supports [WebDAV](https://irods.org/2015/04/how-to-drag-and-drop-access-to-irods-with-webdav/).

**Comment by theferrit32** [comment]
iCAT in docker instance can be connected to via [Davrods](https://github.com/UtrechtUniversity/davrods), which provides an apache/httpd wrapper around the irods filesystem.  

We can set up additional software in the docker workspace that installs and configures davrods and points it to stars-fuse.renci.org where we have a test instance of iRods/icat running in docker.

davrods is just a module to httpd, and runs on port 80 by default.  I have run a centos7 docker image (like our docker workspace) forwarding host port 90 to the container port 80, and it prompts for the irods user/pass and then shows the current contents of the stars-fuse irods instance.

![screen shot 2017-12-18 at 12 00 07 pm](https://user-images.githubusercontent.com/2839238/34118094-c259cc90-e3eb-11e7-97f1-c28cfa8c9b38.png)

**Comment by theferrit32** [comment]
This can be connected to in Mac Finder by selecting Go > Connect To Server..., then entering the iRODS user/pass in the registered user fields.  For the stars-fuse instance this is rods/rods.  

Finder view of same iRODS state as above:
![screen shot 2017-12-18 at 12 13 58 pm](https://user-images.githubusercontent.com/2839238/34118681-8b4c969a-e3ed-11e7-846a-b6ce5751c692.png)

I can also delete a file, like test0. 

I can add a file to the irods instance through Davrods by creating the file locally and using drag-and-drop into the server browser in Finder. 
![screen shot 2017-12-18 at 12 16 35 pm](https://user-images.githubusercontent.com/2839238/34118756-c98d46ca-e3ed-11e7-9e52-78c2dc8f5695.png)

**Comment by stevencox** [comment]
This looks very good.

**Comment by stevencox** [comment]
Is this checked in as something modular in our docker container(s)?

**Comment by theferrit32** [comment]
I am working now on restructuring the single previous docker image into 
- datacommons-base image that has cwltool + irods fuse + irods webdav set up on it
- datacommons-jupyter image that inherits from datacommons-base and has jypyter, the WES fork, and sparkmagic on it

**Comment by stevencox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add DavRODS (WebDAV for iRODS) integration to the workspace for computation base Docker image.](https://trello.com/c/Iww64XUD/10-add-davrods-webdav-for-irods-integration-to-the-workspace-for-computation-base-docker-image)
